language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: ABRN+Zv9i3jY/6k5IcY3AxqI8Fel5K4vnyZGesKdnmdqGBDWpeZHE06S19m4BkA3n4kIRDkyclxrlzwy3QJAQgib72n9Y8ART26yfvR9t/rZ423A86fkt0DAldTej43pUJJwStSunuImbJSuk8zq8E7ytcPMdBscMs7xbACch8DhgjLasb6EjTkhlhG5tNR1fdMe7/tPpSkGNKv8gfx6n7Xo3ni+RHz5pXD6RbUTDJp7uSHwCJ2DPoajZ1W+VXAb+dD1DfwLSHKRYh2xcvJaXFtBnpl1YFhZNKSAx11eKPYBGTGPpSyH25GssTQRmeiG1iTXuJIEBOoXskKeJTvHF+Wf6eL/PGuN6nI+4yDgeBg3K760f8LhKiFInrLz8imV3EXsKoIXjn9vKxJbRFYuZMKEsufGgwfTVbirwFNixo1vYwT50UuxpS+H91C1Lj7rPN5gfhNKEwSsTcz/x8LhGnEfTw98h4KGOxJbU+tAiKzuuPx51JNX9clMVvzfTxUUL53JtxJxOceZqFumIXCFiUWyOwmRWDIBztDkZbdhC9ls2fOEkiwD6aTjg9OAp3yJ7ri9QMy5fO9LiTuEvxNxNwo/yyn1kfM1wYHC/enEHCQZIeYVHb3VRiOVQacWOGvE+MEzbl8JTWCdzlc05ceKqYmVAIn4E+yxVPrkVa7KfQk=
  app: morning-anchorage-20343
  on:
    repo: jayshol/react-trello-testing
