language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: WuVhcH3Za89wJNx3wrBxKCF784H0uNfMiCvH8DhAquG+176/BJIFOYlW21mR++mEhcnk0amGsqTzGKyvqc38krTrRqZXxUquBWYik193J9TN2GO1rKb1ZUJ8yHKe23BV81ofTyauQsbAfjgLCJmB7GIO8lRRW2JRxHP1P65Fyctzz3Q+czuYMn6JiY+sImf/rw/3/M/LRf2i3YztzxwtAkCoJfXqYgvoxac+S+8cixrGgsMRV2c9C0mc80FRcnAvhW3mVA3GgaKR/fJhV/fZeuwC44TaNAb01DjN1Vvi0ORjnlYpTFlG4R23H1T9GKMzAygJgB5ciMn8aUyeh1avx24RW6LrmF5Xq3tF0zVj7UHRTmpIgUOaZ1VXbW5M83WAkbPKoRO7b6QU7wOluXI6Rcx+JFEkLzjB3iMn1pcnjNh2T1zK5BLm23v+HVjt2jXBZX+MXA3SlLVipIrxKFlsVrGQWLaEq1fWNkZxCNiv3vrzHZ1Eia4GKjDbKu4M6isgK/cMzQzuQIlstO/nAo2KVR7YsOPxC7j/OrgY1CBvRuTxnJcgrMcsAttu3mcUk1K0FNQ1ta5BSufbA5RDAE3bxUooBO6i9ktDwE7UMAVXZ+2qK83eYilQsS5DK7UlNkhnZPcBC9a3nuVoltL4BtLtGKDTq0Hzx5qVq2E0OSSEo64=
  app: react-trello-testing
  on:
    repo: jayshol/react-trello-testing
